# CUSTOM VARIABLES
# _FUNCTION_NAME_ = The executable function name, should match index.js.
# _SERVICE_NAME_ = Service name for Cloud Run.
# _FUNCTION_REGION_ = The Region to deploy the function to.
# _CLUSTER_NAME_ = The Cloud Run on GKE cluster name.
# _CLUSTER_LOCATION_ = The Cloud Run on GKE cluster location (master zone).
# _RUN_REGION_ = The Cloud Run region to deploy to.

steps:
# Build image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=gcr.io/$PROJECT_ID/${_SERVICE_NAME_}:$SHORT_SHA'
    - '.'
  id: 'build'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'tag'
    - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME_}:$SHORT_SHA'
    - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME_}:latest'
  wait_for: ['build']
  id: 'tag'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME_}:$SHORT_SHA'
  id: 'push_commit'
  wait_for: ['tag']

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME_}:latest'
  id: 'push_latest'
  wait_for: ['tag']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'functions'
    - 'deploy'
    - '${_FUNCTION_NAME_}'
    - '--runtime=nodejs10'
    - '--trigger-http'
    - '--region=${_FUNCTION_REGION_}'
    - '--set-env-vars'
    - 'MESSAGE=Hello Serverless London ${_FUNCTION_REGION_}'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'beta'
    - 'run'
    - 'deploy'
    - '${_SERVICE_NAME_}'
    - '--image=gcr.io/$PROJECT_ID/${_SERVICE_NAME_}:$SHORT_SHA'
    - '--cluster=${_CLUSTER_NAME_}'
    - '--cluster-location=${_CLUSTER_LOCATION_}'
    - '--set-env-vars'
    - 'MESSAGE=Hello Serverless London (Cloud Run GKE ${_CLUSTER_LOCATION_})'
  wait_for: ['push_commit', 'push_latest']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'beta'
    - 'run'
    - 'deploy'
    - '${_SERVICE_NAME_}'
    - '--image=gcr.io/$PROJECT_ID/${_SERVICE_NAME_}:$SHORT_SHA'
    - '--region=${_RUN_REGION_}'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'MESSAGE=Hello Cloud Next 2019 (Cloud Run ${_RUN_REGION_})'
  wait_for: ['push_commit', 'push_latest']
